acl red_interna {
  127.0.0.1;
  192.168.40.0/24;
  192.168.41.0/24;
  192.168.42.0/24;
  192.168.43.0/25;
  192.168.43.128/26;
  192.168.43.252/30;
};

options {
  directory "/var/bind";
  listen-on { any; };
  listen-on-v6 { none; };
  allow-query { red_interna; };
  allow-transfer { none; };
  recursion yes;
  allow-recursion { red_interna; };
  allow-query-cache { red_interna; };
  forwarders { 192.168.122.1; };
  pid-file "/var/run/named/named.pid";
};

zone "grupo4.test" IN {
  type master;
  file "db.grupo4.test";
  allow-update { none; };
};